name: Rustified
main: me.perotin.rustified.Rustified
version: ${project.version}
author: Perotin
api-version: 1.13
commands:
   blueprint:
      aliases: [blueprints, bp, bps]
      description: Base command for blue prints
   research:
      description: Get the blueprint for an item of which you already have one.
